apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "adguard-home.fullname" . }}-config
data:
  {{- range $path, $_ := $.Files.Glob "config/*" }}
  {{- base $path | nindent 2 }}: |
{{ tpl ($.Files.Get $path) $ | indent 4}}
  {{- end }}