apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adguard-home.fullname" . }}
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "adguard-home.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "adguard-home.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "adguard-home.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AGH_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: {{ include "adguard-home.fullname" . }}-config
                  key: AdGuardHome.yaml
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: api
              containerPort: 3000
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: adguard-work
              mountPath: /opt/adguardhome/work
            - name: adguard-config
              mountPath: /opt/adguardhome/conf
        - name: exporter
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "ghcr.io/henrywhitaker3/adguard-exporter:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9618
              name: metrics
              protocol: TCP
          env:
            - name: ADGUARD_SERVERS
              value: "https://dns.fawenyo.pp.ua"
            - name: ADGUARD_USERNAMES
              value: {{ .Values.auth.name | quote }}
            - name: ADGUARD_PASSWORDS
              value: {{ .Values.auth.password | quote }}
            - name: INTERVAL
              value: "30s"
          ports:
            - containerPort: {{ .Values.exporter.port }}
              name: metrics
              protocol: TCP
          resources:
            {{- toYaml .Values.exporter.resources | nindent 12 }}
      volumes:
        - name: adguard-work
          persistentVolumeClaim:
            claimName: {{ include "adguard-home.fullname" . }}-work
        - name: adguard-config
          persistentVolumeClaim:
            claimName: {{ include "adguard-home.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
