apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "adguard-home.fullname" . }}-work
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- if (lookup "v1" "PersistentVolumeClaim" "{{ .Release.Namespace }}" "{{ include 'adguard-home.fullname' . }}-work") }}
  volumeName: {{ (lookup "v1" "PersistentVolumeClaim" "{{ .Release.Namespace }}" "{{ include 'adguard-home.fullname' . }}-work").spec.volumeName }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "adguard-home.fullname" . }}-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- if (lookup "v1" "PersistentVolumeClaim" "{{ .Release.Namespace }}" "{{ include 'adguard-home.fullname' . }}-config") }}
  volumeName: {{ (lookup "v1" "PersistentVolumeClaim" "{{ .Release.Namespace }}" "{{ include 'adguard-home.fullname' . }}-config").spec.volumeName }}
  {{- end }}
