apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "adguard-home.fullname" . }}
spec:
  selector:
    matchLabels:
      app: exporter
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
