apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: doh-service
spec:
  hosts: {{ .Values.hosts }}
  gateways: {{ .Values.gateways }}
  tls:	
  - match:	
    - port: 443
      sniHosts: {{ .Values.hosts }}
    route:
    - destination:
        host: {{ include "adguard-home.fullname" . }}
        port:
          number: 443
